<?php

namespace RenowazeBundle\Repository;

/**
 * BadWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadWordRepository extends \Doctrine\ORM\EntityRepository
{
}
